apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "dokuwiki.fullname" . }}-pvc 
  labels:
    {{- include "dokuwiki.labels" . | nindent 4 }}
    app.kubernetes.io/component: dokuwiki-data
spec:
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end }}
  accessModes:
    {{- toYaml .Values.persistence.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  {{- with .Values.persistence.selector }}
  selector:
    {{- toYaml . | nindent 4 }}
  {{- end }}